apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-api
  labels:
    app: synergychat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-api
  template:
    metadata:
      labels:
        app: synergychat-api
    spec:
      volumes:
      - name: synergychat-api-volume
        persistentVolumeClaim:
          claimName: synergychat-api-pvc
      containers:
      - name: synergychat-api
        resources:
          limits:
            memory: "12Mi"
            cpu: "50m"
        volumeMounts:
        - name: synergychat-api-volume
          mountPath: /persist
        image: bootdotdev/synergychat-api:latest
        envFrom:
          - configMapRef:
              name: synergychat-api-configmap
        