apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  namespace: crawler
  labels:
    app: synergychat-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      volumes:
        - name: cache-volume
          emptyDir: {}
      containers:
      - name: synergychat-crawler-1
        resources:
          limits:
            memory: "12Mi"
            cpu: "50m"
        image: bootdotdev/synergychat-crawler:latest
        envFrom:
          - configMapRef:
              name: synergychat-crawler-configmap
        
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
        
      - name: synergychat-crawler-2
        image: bootdotdev/synergychat-crawler:latest
        resources:
          limits:
            memory: "12Mi"
            cpu: "50m"
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
        env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_2
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH
      - name: synergychat-crawler-3
        image: bootdotdev/synergychat-crawler:latest
        resources:
          limits:
            memory: "12Mi"
            cpu: "50m"
        volumeMounts:
          - name: cache-volume
            mountPath: /cache
        env:
        - name: CRAWLER_PORT
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_PORT_3
        - name: CRAWLER_KEYWORDS
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_KEYWORDS
        - name: CRAWLER_DB_PATH
          valueFrom:
            configMapKeyRef:
              name: synergychat-crawler-configmap
              key: CRAWLER_DB_PATH